/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.Color;
import javax.swing.JLabel;


/**
 *
 * @author Guille López
 */
public class PanelColores extends javax.swing.JPanel {
    //color inicial
    public Color colorSeleccionado = Color.BLACK;
    
    /**
     * Creates new form PanelColores
     */
    public PanelColores() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Color1 = new javax.swing.JLabel();
        Color2 = new javax.swing.JLabel();
        Color3 = new javax.swing.JLabel();
        Color4 = new javax.swing.JLabel();
        Color5 = new javax.swing.JLabel();
        Color6 = new javax.swing.JLabel();
        Color7 = new javax.swing.JLabel();
        Color8 = new javax.swing.JLabel();
        Color9 = new javax.swing.JLabel();
        Color10 = new javax.swing.JLabel();
        Color11 = new javax.swing.JLabel();
        Color12 = new javax.swing.JLabel();
        Color13 = new javax.swing.JLabel();
        Color14 = new javax.swing.JLabel();
        Color15 = new javax.swing.JLabel();
        Color16 = new javax.swing.JLabel();
        Color17 = new javax.swing.JLabel();
        Color18 = new javax.swing.JLabel();
        Color19 = new javax.swing.JLabel();
        Color20 = new javax.swing.JLabel();
        Color21 = new javax.swing.JLabel();
        Color22 = new javax.swing.JLabel();
        Color23 = new javax.swing.JLabel();
        colorActual = new javax.swing.JLabel();

        Color1.setBackground(new java.awt.Color(255, 0, 0));
        Color1.setOpaque(true);
        Color1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color1MousePressed(evt);
            }
        });

        Color2.setBackground(new java.awt.Color(0, 102, 255));
        Color2.setOpaque(true);
        Color2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color2MousePressed(evt);
            }
        });

        Color3.setBackground(new java.awt.Color(0, 204, 0));
        Color3.setOpaque(true);
        Color3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color3MousePressed(evt);
            }
        });

        Color4.setBackground(new java.awt.Color(255, 255, 0));
        Color4.setOpaque(true);
        Color4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color4MousePressed(evt);
            }
        });

        Color5.setBackground(new java.awt.Color(0, 0, 0));
        Color5.setOpaque(true);
        Color5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color5MousePressed(evt);
            }
        });

        Color6.setBackground(new java.awt.Color(255, 255, 255));
        Color6.setOpaque(true);
        Color6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color6MousePressed(evt);
            }
        });

        Color7.setBackground(new java.awt.Color(255, 102, 0));
        Color7.setOpaque(true);
        Color7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color7MousePressed(evt);
            }
        });

        Color8.setBackground(new java.awt.Color(255, 102, 153));
        Color8.setOpaque(true);
        Color8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color8MousePressed(evt);
            }
        });

        Color9.setBackground(new java.awt.Color(102, 102, 102));
        Color9.setOpaque(true);
        Color9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color9MousePressed(evt);
            }
        });

        Color10.setBackground(new java.awt.Color(204, 0, 204));
        Color10.setOpaque(true);
        Color10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color10MousePressed(evt);
            }
        });

        Color11.setBackground(new java.awt.Color(0, 204, 204));
        Color11.setOpaque(true);
        Color11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color11MousePressed(evt);
            }
        });

        Color12.setBackground(new java.awt.Color(51, 51, 51));
        Color12.setOpaque(true);
        Color12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color12MousePressed(evt);
            }
        });

        Color13.setBackground(new java.awt.Color(153, 255, 51));
        Color13.setOpaque(true);
        Color13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color13MousePressed(evt);
            }
        });

        Color14.setBackground(new java.awt.Color(153, 153, 255));
        Color14.setOpaque(true);
        Color14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color14MousePressed(evt);
            }
        });

        Color15.setBackground(new java.awt.Color(204, 153, 0));
        Color15.setOpaque(true);
        Color15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color15MousePressed(evt);
            }
        });

        Color16.setBackground(new java.awt.Color(0, 153, 0));
        Color16.setOpaque(true);
        Color16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color16MousePressed(evt);
            }
        });

        Color17.setBackground(new java.awt.Color(0, 153, 153));
        Color17.setOpaque(true);
        Color17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color17MousePressed(evt);
            }
        });

        Color18.setBackground(new java.awt.Color(153, 255, 153));
        Color18.setOpaque(true);
        Color18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color18MousePressed(evt);
            }
        });

        Color19.setBackground(new java.awt.Color(0, 51, 51));
        Color19.setOpaque(true);
        Color19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color19MousePressed(evt);
            }
        });

        Color20.setBackground(new java.awt.Color(51, 51, 0));
        Color20.setOpaque(true);
        Color20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color20MousePressed(evt);
            }
        });

        Color21.setBackground(new java.awt.Color(51, 0, 51));
        Color21.setOpaque(true);
        Color21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color21MousePressed(evt);
            }
        });

        Color22.setBackground(new java.awt.Color(0, 0, 51));
        Color22.setOpaque(true);
        Color22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Color22MousePressed(evt);
            }
        });

        Color23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Color23.setText("Color actual:");

        colorActual.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Color23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colorActual, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Color2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Color4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Color6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Color8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Color10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Color12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Color14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Color16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Color18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Color20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Color22, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Color1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Color3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Color5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Color7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Color9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Color11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Color13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Color15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Color17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Color19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Color21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Color1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Color2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Color4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Color6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Color8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Color10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Color12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Color14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Color16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Color18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Color20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Color22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Color23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colorActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
//selecciona el color del JLabel 
    private void Color1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color1MousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorActual.setBackground(colorSeleccionado);
    }//GEN-LAST:event_Color1MousePressed

    private void Color2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color2MousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorActual.setBackground(colorSeleccionado);
    }//GEN-LAST:event_Color2MousePressed

    private void Color3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color3MousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorActual.setBackground(colorSeleccionado);
    }//GEN-LAST:event_Color3MousePressed

    private void Color4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color4MousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorActual.setBackground(colorSeleccionado);
    }//GEN-LAST:event_Color4MousePressed

    private void Color5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color5MousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorActual.setBackground(colorSeleccionado);
    }//GEN-LAST:event_Color5MousePressed

    private void Color6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color6MousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorActual.setBackground(colorSeleccionado);
    }//GEN-LAST:event_Color6MousePressed

    private void Color7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color7MousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorActual.setBackground(colorSeleccionado);
    }//GEN-LAST:event_Color7MousePressed

    private void Color8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color8MousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorActual.setBackground(colorSeleccionado);
    }//GEN-LAST:event_Color8MousePressed

    private void Color9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color9MousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorActual.setBackground(colorSeleccionado);
    }//GEN-LAST:event_Color9MousePressed

    private void Color10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color10MousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorActual.setBackground(colorSeleccionado);
    }//GEN-LAST:event_Color10MousePressed

    private void Color11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color11MousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorActual.setBackground(colorSeleccionado);
    }//GEN-LAST:event_Color11MousePressed

    private void Color12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color12MousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorActual.setBackground(colorSeleccionado);
    }//GEN-LAST:event_Color12MousePressed

    private void Color13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color13MousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorActual.setBackground(colorSeleccionado);
    }//GEN-LAST:event_Color13MousePressed

    private void Color14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color14MousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorActual.setBackground(colorSeleccionado);
    }//GEN-LAST:event_Color14MousePressed

    private void Color15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color15MousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorActual.setBackground(colorSeleccionado);
    }//GEN-LAST:event_Color15MousePressed

    private void Color16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color16MousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorActual.setBackground(colorSeleccionado);
    }//GEN-LAST:event_Color16MousePressed

    private void Color17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color17MousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorActual.setBackground(colorSeleccionado);
    }//GEN-LAST:event_Color17MousePressed

    private void Color18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color18MousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorActual.setBackground(colorSeleccionado);
    }//GEN-LAST:event_Color18MousePressed

    private void Color19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color19MousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorActual.setBackground(colorSeleccionado);
    }//GEN-LAST:event_Color19MousePressed

    private void Color20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color20MousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorActual.setBackground(colorSeleccionado);
    }//GEN-LAST:event_Color20MousePressed

    private void Color21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color21MousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorActual.setBackground(colorSeleccionado);
    }//GEN-LAST:event_Color21MousePressed

    private void Color22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Color22MousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorActual.setBackground(colorSeleccionado);
    }//GEN-LAST:event_Color22MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Color1;
    private javax.swing.JLabel Color10;
    private javax.swing.JLabel Color11;
    private javax.swing.JLabel Color12;
    private javax.swing.JLabel Color13;
    private javax.swing.JLabel Color14;
    private javax.swing.JLabel Color15;
    private javax.swing.JLabel Color16;
    private javax.swing.JLabel Color17;
    private javax.swing.JLabel Color18;
    private javax.swing.JLabel Color19;
    private javax.swing.JLabel Color2;
    private javax.swing.JLabel Color20;
    private javax.swing.JLabel Color21;
    private javax.swing.JLabel Color22;
    private javax.swing.JLabel Color23;
    private javax.swing.JLabel Color3;
    private javax.swing.JLabel Color4;
    private javax.swing.JLabel Color5;
    private javax.swing.JLabel Color6;
    private javax.swing.JLabel Color7;
    private javax.swing.JLabel Color8;
    private javax.swing.JLabel Color9;
    public javax.swing.JLabel colorActual;
    // End of variables declaration//GEN-END:variables
}
